[package]
name = "bevy-template"
version = "0.1.0"
authors = ["TheRawMeatball <therawmeatball@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = 1

[features]
dev = ["bevy/dynamic"]

[dependencies]
bevy = { version = "0.5.0" }
wgpu = "0.9"
wgpu-types = "0.9.0"
rand = "0.8"
bytemuck = { version = "1.4", features = [ "derive" ] }
image = "0.23"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.3"


[patch.crates-io]
# uncomment if you want to use a local fork
bevy = { path = "../bevy" }


[package.metadata.android]
assets = "assets"
res = "assets/android-res"
icon = "@mipmap/ic_launcher"
build_targets = ["aarch64-linux-android"]
min_sdk_version = 16
target_sdk_version = 29

[package.metadata.android.application]
label = "Shoddy Bevy FN"

[package.metadata.android.application.activity]
orientation = "landscape"

[[package.metadata.android.uses_feature]]
name = "android.hardware.vulkan.level"
required = true
version = 1

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"
